module Actions
  A_PLUS_ONE = :A_PLUS_ONE
  B_PLUS_ONE = :B_PLUS_ONE
  C_PLUS_ONE = :C_PLUS_ONE
  D_PLUS_ONE = :D_PLUS_ONE
  E_PLUS_ONE = :E_PLUS_ONE
  F_PLUS_ONE = :F_PLUS_ONE
  G_PLUS_ONE = :G_PLUS_ONE
  H_PLUS_ONE = :H_PLUS_ONE
end
